"""Lab 3 step 7 - AI-generated test data for calculate_discount.

Generated by Claude from the SAME specification text given in tests/test_calculate_discount_lab3.py
(prompt: "Generate equivalence classes and boundary/edge-case test data, as pytest, for this spec").
Kept unedited except for imports. Run explicitly:  pytest labs/lab-3/ai_generated_discount_cases.py -v
"""
import math
import pytest
from app.tasks import calculate_discount


@pytest.mark.parametrize("price, premium, expected", [
    (100, True, 80), (100, False, 100),
    (0, True, 0), (0, False, 0),
    (0.01, True, 0.008), (0.01, False, 0.01),
    (1, True, 0.8), (50.5, True, 40.4),
    (1e9, True, 8e8),
])
def test_ai_valid(price, premium, expected):
    assert calculate_discount(price, premium) == pytest.approx(expected)


@pytest.mark.parametrize("price", [-1, -0.01, -1e9])
@pytest.mark.parametrize("premium", [True, False])
def test_ai_negative_price(price, premium):
    with pytest.raises(ValueError):
        calculate_discount(price, premium)


@pytest.mark.parametrize("price", ["100", "abc", None, [], True])
def test_ai_non_numeric_price(price):
    with pytest.raises(TypeError):
        calculate_discount(price, True)


@pytest.mark.parametrize("price", [float("nan"), float("inf")])
def test_ai_nan_inf(price):
    with pytest.raises(ValueError):
        calculate_discount(price, True)


@pytest.mark.parametrize("flag", [None, "yes", 1, 0])
def test_ai_non_bool_flag(flag):
    with pytest.raises(TypeError):
        calculate_discount(100, flag)


def test_ai_float_precision():
    assert math.isclose(calculate_discount(0.1, True), 0.08)
